spring:  servlet:    multipart:      max-file-size: 3MB
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/azcafe2?serverTimezone=JST
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: nishino.aso@gmail.com
    password: jizlzeuhkrorsarh
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    
azcafe:
  salt: 5fr2FjxT
  avaterbasedir: C:/img
  tokenlimit: 1
  passwordpolicy:   csvoutputdir: C:/output  csvoutputencode: Shift_JIS
  csvuploaddir: C:/upload
  batchdir: c:/batch
  batchfileext: bat 
  codedir: c:/code
  srcPrefix: src_
  gradingjavac: comple_java.bat
  gradingjava: exec_java.bat
  checkstyle: checkstyle_java.bat
  gradingjavascript: exec_javascript.bat  skillmaplimit: 100  studentdenied: ^/user/reset/password$,^/homeroom/update,^/assignment/(edit|create|confirm|insert),^/manage/.*,^user/csvinput  nologindisplay: /,/login,/auth,/logout,/css/.+,/img/.+,/getImage/.+,/favicon.ico,/error/.*  handminus: 5  difficulty:    veasy: 0    easy: 2    normal: 5    diff: 7    vdiff: 10    