package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 解答テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AnswerTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** answer_id. */
	private Integer answerId;

	/** 問題テーブル. */
	private AssignmentTblEntity assignmentTbl;

	/** ユーザー. */
	private UserTblEntity userTbl;

	/** 答え. */
	private String answer;

	/** ファイル名. */
	private String fileName;

	/** 点数. */
	private Integer score;

	/** 正解フラグ. */
	private Integer correctFlg;

	/** 解答いいね 一覧. */
	private Set<AnswerGoodTblEntity> answerGoodTblSet;

	/** コメント 一覧. */
	private Set<CommentTblEntity> commentTblSet;

	/**
	 * コンストラクタ.
	 */
	public AnswerTblEntity() {
		this.answerGoodTblSet = new HashSet<AnswerGoodTblEntity>();
		this.commentTblSet = new HashSet<CommentTblEntity>();
	}

	/**
	 * answer_id を設定します.
	 * 
	 * @param answerId
	 *            answer_id
	 */
	public void setAnswerId(Integer answerId) {
		this.answerId = answerId;
	}

	/**
	 * answer_id を取得します.
	 * 
	 * @return answer_id
	 */
	public Integer getAnswerId() {
		return this.answerId;
	}

	/**
	 * 問題テーブル を設定します.
	 * 
	 * @param assignmentTbl
	 *            問題テーブル
	 */
	public void setAssignmentTbl(AssignmentTblEntity assignmentTbl) {
		this.assignmentTbl = assignmentTbl;
	}

	/**
	 * 問題テーブル を取得します.
	 * 
	 * @return 問題テーブル
	 */
	public AssignmentTblEntity getAssignmentTbl() {
		return this.assignmentTbl;
	}

	/**
	 * ユーザー を設定します.
	 * 
	 * @param userTbl
	 *            ユーザー
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザー を取得します.
	 * 
	 * @return ユーザー
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * 答え を設定します.
	 * 
	 * @param answer
	 *            答え
	 */
	public void setAnswer(String answer) {
		this.answer = answer;
	}

	/**
	 * 答え を取得します.
	 * 
	 * @return 答え
	 */
	public String getAnswer() {
		return this.answer;
	}

	/**
	 * ファイル名 を設定します.
	 * 
	 * @param fileName
	 *            ファイル名
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * ファイル名 を取得します.
	 * 
	 * @return ファイル名
	 */
	public String getFileName() {
		return this.fileName;
	}

	/**
	 * 点数 を設定します.
	 * 
	 * @param score
	 *            点数
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * 点数 を取得します.
	 * 
	 * @return 点数
	 */
	public Integer getScore() {
		return this.score;
	}

	/**
	 * 正解フラグ を設定します.
	 * 
	 * @param correctFlg
	 *            正解フラグ
	 */
	public void setCorrectFlg(Integer correctFlg) {
		this.correctFlg = correctFlg;
	}

	/**
	 * 正解フラグ を取得します.
	 * 
	 * @return 正解フラグ
	 */
	public Integer getCorrectFlg() {
		return this.correctFlg;
	}

	/**
	 * 解答いいね 一覧を設定します.
	 * 
	 * @param answerGoodTblSet
	 *            解答いいね 一覧
	 */
	public void setAnswerGoodTblSet(Set<AnswerGoodTblEntity> answerGoodTblSet) {
		this.answerGoodTblSet = answerGoodTblSet;
	}

	/**
	 * 解答いいね を追加します.
	 * 
	 * @param answerGoodTbl
	 *            解答いいね
	 */
	public void addAnswerGoodTbl(AnswerGoodTblEntity answerGoodTbl) {
		this.answerGoodTblSet.add(answerGoodTbl);
	}

	/**
	 * 解答いいね 一覧を取得します.
	 * 
	 * @return 解答いいね 一覧
	 */
	public Set<AnswerGoodTblEntity> getAnswerGoodTblSet() {
		return this.answerGoodTblSet;
	}

	/**
	 * コメント 一覧を設定します.
	 * 
	 * @param commentTblSet
	 *            コメント 一覧
	 */
	public void setCommentTblSet(Set<CommentTblEntity> commentTblSet) {
		this.commentTblSet = commentTblSet;
	}

	/**
	 * コメント を追加します.
	 * 
	 * @param commentTbl
	 *            コメント
	 */
	public void addCommentTbl(CommentTblEntity commentTbl) {
		this.commentTblSet.add(commentTbl);
	}

	/**
	 * コメント 一覧を取得します.
	 * 
	 * @return コメント 一覧
	 */
	public Set<CommentTblEntity> getCommentTblSet() {
		return this.commentTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((answerId == null) ? 0 : answerId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AnswerTblEntity other = (AnswerTblEntity) obj;
		if (answerId == null) {
			if (other.answerId != null) {
				return false;
			}
		} else if (!answerId.equals(other.answerId)) {
			return false;
		}
		return true;
	}

}
