package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 解答テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AnswerTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** answer_id. */
	private Integer answerId;

	/** ユーザー. */
	private UserTblEntity userTbl;

	/** 問題テーブル. */
	private AssignmentTblEntity assignmentTbl;

	/** 点数. */
	private Integer score;

	/** 正解フラグ. */
	private Integer correctFlg;

	/** チェックスタイルのメッセージ. */
	private String checkStyleMsg;

	/** ソースコードの点数. */
	private Integer sourceScore;

	/** 出力の点数. */
	private Integer outputScore;

	/** 解答日付. */
	private Date answerDate;

	/** ポイント. */
	private Integer point;

	/** 提出回数. */
	private Integer handNum;

	/** 解答詳細テーブル 一覧. */
	private Set<AnswerDetailTblEntity> answerDetailTblSet;

	/** 解答いいね 一覧. */
	private Set<AnswerGoodTblEntity> answerGoodTblSet;

	/** コメント 一覧. */
	private Set<CommentTblEntity> commentTblSet;

	/** テストケースごとの答えテーブル 一覧. */
	private Set<TestCaseAnswerTblEntity> testCaseAnswerTblSet;

	/**
	 * コンストラクタ.
	 */
	public AnswerTblEntity() {
		this.answerDetailTblSet = new HashSet<AnswerDetailTblEntity>();
		this.answerGoodTblSet = new HashSet<AnswerGoodTblEntity>();
		this.commentTblSet = new HashSet<CommentTblEntity>();
		this.testCaseAnswerTblSet = new HashSet<TestCaseAnswerTblEntity>();
	}

	/**
	 * answer_id を設定します.
	 * 
	 * @param answerId
	 *            answer_id
	 */
	public void setAnswerId(Integer answerId) {
		this.answerId = answerId;
	}

	/**
	 * answer_id を取得します.
	 * 
	 * @return answer_id
	 */
	public Integer getAnswerId() {
		return this.answerId;
	}

	/**
	 * ユーザー を設定します.
	 * 
	 * @param userTbl
	 *            ユーザー
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザー を取得します.
	 * 
	 * @return ユーザー
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * 問題テーブル を設定します.
	 * 
	 * @param assignmentTbl
	 *            問題テーブル
	 */
	public void setAssignmentTbl(AssignmentTblEntity assignmentTbl) {
		this.assignmentTbl = assignmentTbl;
	}

	/**
	 * 問題テーブル を取得します.
	 * 
	 * @return 問題テーブル
	 */
	public AssignmentTblEntity getAssignmentTbl() {
		return this.assignmentTbl;
	}

	/**
	 * 点数 を設定します.
	 * 
	 * @param score
	 *            点数
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * 点数 を取得します.
	 * 
	 * @return 点数
	 */
	public Integer getScore() {
		return this.score;
	}

	/**
	 * 正解フラグ を設定します.
	 * 
	 * @param correctFlg
	 *            正解フラグ
	 */
	public void setCorrectFlg(Integer correctFlg) {
		this.correctFlg = correctFlg;
	}

	/**
	 * 正解フラグ を取得します.
	 * 
	 * @return 正解フラグ
	 */
	public Integer getCorrectFlg() {
		return this.correctFlg;
	}

	/**
	 * チェックスタイルのメッセージ を設定します.
	 * 
	 * @param checkStyleMsg
	 *            チェックスタイルのメッセージ
	 */
	public void setCheckStyleMsg(String checkStyleMsg) {
		this.checkStyleMsg = checkStyleMsg;
	}

	/**
	 * チェックスタイルのメッセージ を取得します.
	 * 
	 * @return チェックスタイルのメッセージ
	 */
	public String getCheckStyleMsg() {
		return this.checkStyleMsg;
	}

	/**
	 * ソースコードの点数 を設定します.
	 * 
	 * @param sourceScore
	 *            ソースコードの点数
	 */
	public void setSourceScore(Integer sourceScore) {
		this.sourceScore = sourceScore;
	}

	/**
	 * ソースコードの点数 を取得します.
	 * 
	 * @return ソースコードの点数
	 */
	public Integer getSourceScore() {
		return this.sourceScore;
	}

	/**
	 * 出力の点数 を設定します.
	 * 
	 * @param outputScore
	 *            出力の点数
	 */
	public void setOutputScore(Integer outputScore) {
		this.outputScore = outputScore;
	}

	/**
	 * 出力の点数 を取得します.
	 * 
	 * @return 出力の点数
	 */
	public Integer getOutputScore() {
		return this.outputScore;
	}

	/**
	 * 解答日付 を設定します.
	 * 
	 * @param answerDate
	 *            解答日付
	 */
	public void setAnswerDate(Date answerDate) {
		this.answerDate = answerDate;
	}

	/**
	 * 解答日付 を取得します.
	 * 
	 * @return 解答日付
	 */
	public Date getAnswerDate() {
		return this.answerDate;
	}

	/**
	 * ポイント を設定します.
	 * 
	 * @param point
	 *            ポイント
	 */
	public void setPoint(Integer point) {
		this.point = point;
	}

	/**
	 * ポイント を取得します.
	 * 
	 * @return ポイント
	 */
	public Integer getPoint() {
		return this.point;
	}

	/**
	 * 提出回数 を設定します.
	 * 
	 * @param handNum
	 *            提出回数
	 */
	public void setHandNum(Integer handNum) {
		this.handNum = handNum;
	}

	/**
	 * 提出回数 を取得します.
	 * 
	 * @return 提出回数
	 */
	public Integer getHandNum() {
		return this.handNum;
	}

	/**
	 * 解答詳細テーブル 一覧を設定します.
	 * 
	 * @param answerDetailTblSet
	 *            解答詳細テーブル 一覧
	 */
	public void setAnswerDetailTblSet(Set<AnswerDetailTblEntity> answerDetailTblSet) {
		this.answerDetailTblSet = answerDetailTblSet;
	}

	/**
	 * 解答詳細テーブル を追加します.
	 * 
	 * @param answerDetailTbl
	 *            解答詳細テーブル
	 */
	public void addAnswerDetailTbl(AnswerDetailTblEntity answerDetailTbl) {
		this.answerDetailTblSet.add(answerDetailTbl);
	}

	/**
	 * 解答詳細テーブル 一覧を取得します.
	 * 
	 * @return 解答詳細テーブル 一覧
	 */
	public Set<AnswerDetailTblEntity> getAnswerDetailTblSet() {
		return this.answerDetailTblSet;
	}

	/**
	 * 解答いいね 一覧を設定します.
	 * 
	 * @param answerGoodTblSet
	 *            解答いいね 一覧
	 */
	public void setAnswerGoodTblSet(Set<AnswerGoodTblEntity> answerGoodTblSet) {
		this.answerGoodTblSet = answerGoodTblSet;
	}

	/**
	 * 解答いいね を追加します.
	 * 
	 * @param answerGoodTbl
	 *            解答いいね
	 */
	public void addAnswerGoodTbl(AnswerGoodTblEntity answerGoodTbl) {
		this.answerGoodTblSet.add(answerGoodTbl);
	}

	/**
	 * 解答いいね 一覧を取得します.
	 * 
	 * @return 解答いいね 一覧
	 */
	public Set<AnswerGoodTblEntity> getAnswerGoodTblSet() {
		return this.answerGoodTblSet;
	}

	/**
	 * コメント 一覧を設定します.
	 * 
	 * @param commentTblSet
	 *            コメント 一覧
	 */
	public void setCommentTblSet(Set<CommentTblEntity> commentTblSet) {
		this.commentTblSet = commentTblSet;
	}

	/**
	 * コメント を追加します.
	 * 
	 * @param commentTbl
	 *            コメント
	 */
	public void addCommentTbl(CommentTblEntity commentTbl) {
		this.commentTblSet.add(commentTbl);
	}

	/**
	 * コメント 一覧を取得します.
	 * 
	 * @return コメント 一覧
	 */
	public Set<CommentTblEntity> getCommentTblSet() {
		return this.commentTblSet;
	}

	/**
	 * テストケースごとの答えテーブル 一覧を設定します.
	 * 
	 * @param testCaseAnswerTblSet
	 *            テストケースごとの答えテーブル 一覧
	 */
	public void setTestCaseAnswerTblSet(Set<TestCaseAnswerTblEntity> testCaseAnswerTblSet) {
		this.testCaseAnswerTblSet = testCaseAnswerTblSet;
	}

	/**
	 * テストケースごとの答えテーブル を追加します.
	 * 
	 * @param testCaseAnswerTbl
	 *            テストケースごとの答えテーブル
	 */
	public void addTestCaseAnswerTbl(TestCaseAnswerTblEntity testCaseAnswerTbl) {
		this.testCaseAnswerTblSet.add(testCaseAnswerTbl);
	}

	/**
	 * テストケースごとの答えテーブル 一覧を取得します.
	 * 
	 * @return テストケースごとの答えテーブル 一覧
	 */
	public Set<TestCaseAnswerTblEntity> getTestCaseAnswerTblSet() {
		return this.testCaseAnswerTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((answerId == null) ? 0 : answerId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AnswerTblEntity other = (AnswerTblEntity) obj;
		if (answerId == null) {
			if (other.answerId != null) {
				return false;
			}
		} else if (!answerId.equals(other.answerId)) {
			return false;
		}
		return true;
	}

}
