package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;

/**
 * 解答詳細テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AnswerDetailTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 解答詳細ID. */
	private Integer answerDetailId;

	/** 解答テーブル. */
	private AnswerTblEntity answerTbl;

	/** ファイル名. */
	private String filename;

	/** 解答. */
	private String answer;

	/**
	 * コンストラクタ.
	 */
	public AnswerDetailTblEntity() {
	}

	/**
	 * 解答詳細ID を設定します.
	 * 
	 * @param answerDetailId
	 *            解答詳細ID
	 */
	public void setAnswerDetailId(Integer answerDetailId) {
		this.answerDetailId = answerDetailId;
	}

	/**
	 * 解答詳細ID を取得します.
	 * 
	 * @return 解答詳細ID
	 */
	public Integer getAnswerDetailId() {
		return this.answerDetailId;
	}

	/**
	 * 解答テーブル を設定します.
	 * 
	 * @param answerTbl
	 *            解答テーブル
	 */
	public void setAnswerTbl(AnswerTblEntity answerTbl) {
		this.answerTbl = answerTbl;
	}

	/**
	 * 解答テーブル を取得します.
	 * 
	 * @return 解答テーブル
	 */
	public AnswerTblEntity getAnswerTbl() {
		return this.answerTbl;
	}

	/**
	 * ファイル名 を設定します.
	 * 
	 * @param filename
	 *            ファイル名
	 */
	public void setFilename(String filename) {
		this.filename = filename;
	}

	/**
	 * ファイル名 を取得します.
	 * 
	 * @return ファイル名
	 */
	public String getFilename() {
		return this.filename;
	}

	/**
	 * 解答 を設定します.
	 * 
	 * @param answer
	 *            解答
	 */
	public void setAnswer(String answer) {
		this.answer = answer;
	}

	/**
	 * 解答 を取得します.
	 * 
	 * @return 解答
	 */
	public String getAnswer() {
		return this.answer;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((answerDetailId == null) ? 0 : answerDetailId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AnswerDetailTblEntity other = (AnswerDetailTblEntity) obj;
		if (answerDetailId == null) {
			if (other.answerDetailId != null) {
				return false;
			}
		} else if (!answerDetailId.equals(other.answerDetailId)) {
			return false;
		}
		return true;
	}

}
