package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 解答いいね モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AnswerGoodTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 解答テーブル. */
	private AnswerTblEntity answerTbl;

	/** ユーザー. */
	private UserTblEntity userTbl;

	/** イイネをした日時. */
	private Date goodDate;

	/**
	 * コンストラクタ.
	 */
	public AnswerGoodTblEntity() {
	}

	/**
	 * 解答テーブル を設定します.
	 * 
	 * @param answerTbl
	 *            解答テーブル
	 */
	public void setAnswerTbl(AnswerTblEntity answerTbl) {
		this.answerTbl = answerTbl;
	}

	/**
	 * 解答テーブル を取得します.
	 * 
	 * @return 解答テーブル
	 */
	public AnswerTblEntity getAnswerTbl() {
		return this.answerTbl;
	}

	/**
	 * ユーザー を設定します.
	 * 
	 * @param userTbl
	 *            ユーザー
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザー を取得します.
	 * 
	 * @return ユーザー
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * イイネをした日時 を設定します.
	 * 
	 * @param goodDate
	 *            イイネをした日時
	 */
	public void setGoodDate(Date goodDate) {
		this.goodDate = goodDate;
	}

	/**
	 * イイネをした日時 を取得します.
	 * 
	 * @return イイネをした日時
	 */
	public Date getGoodDate() {
		return this.goodDate;
	}


}
