package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 問題イイネテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AssignmentGoodTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** assignment_good_id. */
	private Integer assignmentGoodId;

	/** 問題テーブル. */
	private AssignmentTblEntity assignmentTbl;

	/** ユーザー. */
	private UserTblEntity userTbl;

	/** イイネをした日時. */
	private Date goodDate;

	/**
	 * コンストラクタ.
	 */
	public AssignmentGoodTblEntity() {
	}

	/**
	 * assignment_good_id を設定します.
	 * 
	 * @param assignmentGoodId
	 *            assignment_good_id
	 */
	public void setAssignmentGoodId(Integer assignmentGoodId) {
		this.assignmentGoodId = assignmentGoodId;
	}

	/**
	 * assignment_good_id を取得します.
	 * 
	 * @return assignment_good_id
	 */
	public Integer getAssignmentGoodId() {
		return this.assignmentGoodId;
	}

	/**
	 * 問題テーブル を設定します.
	 * 
	 * @param assignmentTbl
	 *            問題テーブル
	 */
	public void setAssignmentTbl(AssignmentTblEntity assignmentTbl) {
		this.assignmentTbl = assignmentTbl;
	}

	/**
	 * 問題テーブル を取得します.
	 * 
	 * @return 問題テーブル
	 */
	public AssignmentTblEntity getAssignmentTbl() {
		return this.assignmentTbl;
	}

	/**
	 * ユーザー を設定します.
	 * 
	 * @param userTbl
	 *            ユーザー
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザー を取得します.
	 * 
	 * @return ユーザー
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * イイネをした日時 を設定します.
	 * 
	 * @param goodDate
	 *            イイネをした日時
	 */
	public void setGoodDate(Date goodDate) {
		this.goodDate = goodDate;
	}

	/**
	 * イイネをした日時 を取得します.
	 * 
	 * @return イイネをした日時
	 */
	public Date getGoodDate() {
		return this.goodDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((assignmentGoodId == null) ? 0 : assignmentGoodId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AssignmentGoodTblEntity other = (AssignmentGoodTblEntity) obj;
		if (assignmentGoodId == null) {
			if (other.assignmentGoodId != null) {
				return false;
			}
		} else if (!assignmentGoodId.equals(other.assignmentGoodId)) {
			return false;
		}
		return true;
	}

}
