package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 自動ログイン モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AutologinTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** autologin_id. */
	private Integer autologinId;

	/** ユーザー. */
	private UserTblEntity userTbl;

	/** token. */
	private String token;

	/** トークンの有効期限. */
	private Date lmitDate;

	/**
	 * コンストラクタ.
	 */
	public AutologinTblEntity() {
	}

	/**
	 * autologin_id を設定します.
	 * 
	 * @param autologinId
	 *            autologin_id
	 */
	public void setAutologinId(Integer autologinId) {
		this.autologinId = autologinId;
	}

	/**
	 * autologin_id を取得します.
	 * 
	 * @return autologin_id
	 */
	public Integer getAutologinId() {
		return this.autologinId;
	}

	/**
	 * ユーザー を設定します.
	 * 
	 * @param userTbl
	 *            ユーザー
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザー を取得します.
	 * 
	 * @return ユーザー
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * token を設定します.
	 * 
	 * @param token
	 *            token
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * token を取得します.
	 * 
	 * @return token
	 */
	public String getToken() {
		return this.token;
	}

	/**
	 * トークンの有効期限 を設定します.
	 * 
	 * @param lmitDate
	 *            トークンの有効期限
	 */
	public void setLmitDate(Date lmitDate) {
		this.lmitDate = lmitDate;
	}

	/**
	 * トークンの有効期限 を取得します.
	 * 
	 * @return トークンの有効期限
	 */
	public Date getLmitDate() {
		return this.lmitDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((autologinId == null) ? 0 : autologinId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AutologinTblEntity other = (AutologinTblEntity) obj;
		if (autologinId == null) {
			if (other.autologinId != null) {
				return false;
			}
		} else if (!autologinId.equals(other.autologinId)) {
			return false;
		}
		return true;
	}

}
