package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * コメント モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CommentTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** comment_id. */
	private Integer commentId;

	/** 解答テーブル. */
	private AnswerTblEntity answerTbl;

	/** ユーザー. */
	private UserTblEntity userTbl;

	/** comment. */
	private String comment;

	/** entry_date. */
	private Date entryDate;

	/**
	 * コンストラクタ.
	 */
	public CommentTblEntity() {
	}

	/**
	 * comment_id を設定します.
	 * 
	 * @param commentId
	 *            comment_id
	 */
	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	/**
	 * comment_id を取得します.
	 * 
	 * @return comment_id
	 */
	public Integer getCommentId() {
		return this.commentId;
	}

	/**
	 * 解答テーブル を設定します.
	 * 
	 * @param answerTbl
	 *            解答テーブル
	 */
	public void setAnswerTbl(AnswerTblEntity answerTbl) {
		this.answerTbl = answerTbl;
	}

	/**
	 * 解答テーブル を取得します.
	 * 
	 * @return 解答テーブル
	 */
	public AnswerTblEntity getAnswerTbl() {
		return this.answerTbl;
	}

	/**
	 * ユーザー を設定します.
	 * 
	 * @param userTbl
	 *            ユーザー
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザー を取得します.
	 * 
	 * @return ユーザー
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * comment を設定します.
	 * 
	 * @param comment
	 *            comment
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * comment を取得します.
	 * 
	 * @return comment
	 */
	public String getComment() {
		return this.comment;
	}

	/**
	 * entry_date を設定します.
	 * 
	 * @param entryDate
	 *            entry_date
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	/**
	 * entry_date を取得します.
	 * 
	 * @return entry_date
	 */
	public Date getEntryDate() {
		return this.entryDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((commentId == null) ? 0 : commentId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CommentTblEntity other = (CommentTblEntity) obj;
		if (commentId == null) {
			if (other.commentId != null) {
				return false;
			}
		} else if (!commentId.equals(other.commentId)) {
			return false;
		}
		return true;
	}

}
