package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 問題グループ モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GroupTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** group_id. */
	private Integer groupId;

	/** グループ名. */
	private String name;

	/** 登録日時. */
	private Date entryDate;

	/** 更新日時. */
	private Date updateDate;

	/** 問題テーブル 一覧. */
	private Set<AssignmentTblEntity> assignmentTblSet;

	/**
	 * コンストラクタ.
	 */
	public GroupTblEntity() {
		this.assignmentTblSet = new HashSet<AssignmentTblEntity>();
	}

	/**
	 * group_id を設定します.
	 * 
	 * @param groupId
	 *            group_id
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * group_id を取得します.
	 * 
	 * @return group_id
	 */
	public Integer getGroupId() {
		return this.groupId;
	}

	/**
	 * グループ名 を設定します.
	 * 
	 * @param name
	 *            グループ名
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * グループ名 を取得します.
	 * 
	 * @return グループ名
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 登録日時 を設定します.
	 * 
	 * @param entryDate
	 *            登録日時
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	/**
	 * 登録日時 を取得します.
	 * 
	 * @return 登録日時
	 */
	public Date getEntryDate() {
		return this.entryDate;
	}

	/**
	 * 更新日時 を設定します.
	 * 
	 * @param updateDate
	 *            更新日時
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * 更新日時 を取得します.
	 * 
	 * @return 更新日時
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * 問題テーブル 一覧を設定します.
	 * 
	 * @param assignmentTblSet
	 *            問題テーブル 一覧
	 */
	public void setAssignmentTblSet(Set<AssignmentTblEntity> assignmentTblSet) {
		this.assignmentTblSet = assignmentTblSet;
	}

	/**
	 * 問題テーブル を追加します.
	 * 
	 * @param assignmentTbl
	 *            問題テーブル
	 */
	public void addAssignmentTbl(AssignmentTblEntity assignmentTbl) {
		this.assignmentTblSet.add(assignmentTbl);
	}

	/**
	 * 問題テーブル 一覧を取得します.
	 * 
	 * @return 問題テーブル 一覧
	 */
	public Set<AssignmentTblEntity> getAssignmentTblSet() {
		return this.assignmentTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((groupId == null) ? 0 : groupId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		GroupTblEntity other = (GroupTblEntity) obj;
		if (groupId == null) {
			if (other.groupId != null) {
				return false;
			}
		} else if (!groupId.equals(other.groupId)) {
			return false;
		}
		return true;
	}

}
