package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 称号マスターテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class LevelTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** level_id. */
	private Integer levelId;

	/** 称号名. */
	private String name;

	/** 説明. */
	private String description;

	/** ユーザー 一覧. */
	private Set<UserTblEntity> userTblSet;

	/**
	 * コンストラクタ.
	 */
	public LevelTblEntity() {
		this.userTblSet = new HashSet<UserTblEntity>();
	}

	/**
	 * level_id を設定します.
	 * 
	 * @param levelId
	 *            level_id
	 */
	public void setLevelId(Integer levelId) {
		this.levelId = levelId;
	}

	/**
	 * level_id を取得します.
	 * 
	 * @return level_id
	 */
	public Integer getLevelId() {
		return this.levelId;
	}

	/**
	 * 称号名 を設定します.
	 * 
	 * @param name
	 *            称号名
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 称号名 を取得します.
	 * 
	 * @return 称号名
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 説明 を設定します.
	 * 
	 * @param description
	 *            説明
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * 説明 を取得します.
	 * 
	 * @return 説明
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * ユーザー 一覧を設定します.
	 * 
	 * @param userTblSet
	 *            ユーザー 一覧
	 */
	public void setUserTblSet(Set<UserTblEntity> userTblSet) {
		this.userTblSet = userTblSet;
	}

	/**
	 * ユーザー を追加します.
	 * 
	 * @param userTbl
	 *            ユーザー
	 */
	public void addUserTbl(UserTblEntity userTbl) {
		this.userTblSet.add(userTbl);
	}

	/**
	 * ユーザー 一覧を取得します.
	 * 
	 * @return ユーザー 一覧
	 */
	public Set<UserTblEntity> getUserTblSet() {
		return this.userTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((levelId == null) ? 0 : levelId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		LevelTblEntity other = (LevelTblEntity) obj;
		if (levelId == null) {
			if (other.levelId != null) {
				return false;
			}
		} else if (!levelId.equals(other.levelId)) {
			return false;
		}
		return true;
	}

}
