package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 称号マスターテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class LevelTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** level_id. */
	private Integer levelId;

	/** 称号名. */
	private String name;

	/** 説明. */
	private String description;

	/** 必要ポイント. */
	private Integer point;

	/** 必要な回答数. */
	private Integer answer;

	/** フォロワー数. */
	private Integer follower;

	/** イイネの数. */
	private Integer good;

	/** コメントの数. */
	private Integer comment;

	/** レベル. */
	private Integer level;

	/** ユーザー称号テーブル 一覧. */
	private Set<UserLevelTblEntity> userLevelTblSet;

	/**
	 * コンストラクタ.
	 */
	public LevelTblEntity() {
		this.userLevelTblSet = new HashSet<UserLevelTblEntity>();
	}

	/**
	 * level_id を設定します.
	 * 
	 * @param levelId
	 *            level_id
	 */
	public void setLevelId(Integer levelId) {
		this.levelId = levelId;
	}

	/**
	 * level_id を取得します.
	 * 
	 * @return level_id
	 */
	public Integer getLevelId() {
		return this.levelId;
	}

	/**
	 * 称号名 を設定します.
	 * 
	 * @param name
	 *            称号名
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 称号名 を取得します.
	 * 
	 * @return 称号名
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 説明 を設定します.
	 * 
	 * @param description
	 *            説明
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * 説明 を取得します.
	 * 
	 * @return 説明
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * 必要ポイント を設定します.
	 * 
	 * @param point
	 *            必要ポイント
	 */
	public void setPoint(Integer point) {
		this.point = point;
	}

	/**
	 * 必要ポイント を取得します.
	 * 
	 * @return 必要ポイント
	 */
	public Integer getPoint() {
		return this.point;
	}

	/**
	 * 必要な回答数 を設定します.
	 * 
	 * @param answer
	 *            必要な回答数
	 */
	public void setAnswer(Integer answer) {
		this.answer = answer;
	}

	/**
	 * 必要な回答数 を取得します.
	 * 
	 * @return 必要な回答数
	 */
	public Integer getAnswer() {
		return this.answer;
	}

	/**
	 * フォロワー数 を設定します.
	 * 
	 * @param follower
	 *            フォロワー数
	 */
	public void setFollower(Integer follower) {
		this.follower = follower;
	}

	/**
	 * フォロワー数 を取得します.
	 * 
	 * @return フォロワー数
	 */
	public Integer getFollower() {
		return this.follower;
	}

	/**
	 * イイネの数 を設定します.
	 * 
	 * @param good
	 *            イイネの数
	 */
	public void setGood(Integer good) {
		this.good = good;
	}

	/**
	 * イイネの数 を取得します.
	 * 
	 * @return イイネの数
	 */
	public Integer getGood() {
		return this.good;
	}

	/**
	 * コメントの数 を設定します.
	 * 
	 * @param comment
	 *            コメントの数
	 */
	public void setComment(Integer comment) {
		this.comment = comment;
	}

	/**
	 * コメントの数 を取得します.
	 * 
	 * @return コメントの数
	 */
	public Integer getComment() {
		return this.comment;
	}

	/**
	 * レベル を設定します.
	 * 
	 * @param level
	 *            レベル
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * レベル を取得します.
	 * 
	 * @return レベル
	 */
	public Integer getLevel() {
		return this.level;
	}

	/**
	 * ユーザー称号テーブル 一覧を設定します.
	 * 
	 * @param userLevelTblSet
	 *            ユーザー称号テーブル 一覧
	 */
	public void setUserLevelTblSet(Set<UserLevelTblEntity> userLevelTblSet) {
		this.userLevelTblSet = userLevelTblSet;
	}

	/**
	 * ユーザー称号テーブル を追加します.
	 * 
	 * @param userLevelTbl
	 *            ユーザー称号テーブル
	 */
	public void addUserLevelTbl(UserLevelTblEntity userLevelTbl) {
		this.userLevelTblSet.add(userLevelTbl);
	}

	/**
	 * ユーザー称号テーブル 一覧を取得します.
	 * 
	 * @return ユーザー称号テーブル 一覧
	 */
	public Set<UserLevelTblEntity> getUserLevelTblSet() {
		return this.userLevelTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((levelId == null) ? 0 : levelId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		LevelTblEntity other = (LevelTblEntity) obj;
		if (levelId == null) {
			if (other.levelId != null) {
				return false;
			}
		} else if (!levelId.equals(other.levelId)) {
			return false;
		}
		return true;
	}

}
