package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 公開設定 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PublicQuestionTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 問題テーブル. */
	private AssignmentTblEntity assignmentTbl;

	/** 新規テーブル. */
	private HomeroomTblEntity homeroomTbl;

	/** 公開設定. */
	private Integer publicState;

	/** 公開開始日時. */
	private Date publicStartDate;

	/** 公開終了日時. */
	private Date publicEndDate;

	/**
	 * コンストラクタ.
	 */
	public PublicQuestionTblEntity() {
	}

	/**
	 * 問題テーブル を設定します.
	 * 
	 * @param assignmentTbl
	 *            問題テーブル
	 */
	public void setAssignmentTbl(AssignmentTblEntity assignmentTbl) {
		this.assignmentTbl = assignmentTbl;
	}

	/**
	 * 問題テーブル を取得します.
	 * 
	 * @return 問題テーブル
	 */
	public AssignmentTblEntity getAssignmentTbl() {
		return this.assignmentTbl;
	}

	/**
	 * 新規テーブル を設定します.
	 * 
	 * @param homeroomTbl
	 *            新規テーブル
	 */
	public void setHomeroomTbl(HomeroomTblEntity homeroomTbl) {
		this.homeroomTbl = homeroomTbl;
	}

	/**
	 * 新規テーブル を取得します.
	 * 
	 * @return 新規テーブル
	 */
	public HomeroomTblEntity getHomeroomTbl() {
		return this.homeroomTbl;
	}

	/**
	 * 公開設定 を設定します.
	 * 
	 * @param publicState
	 *            公開設定
	 */
	public void setPublicState(Integer publicState) {
		this.publicState = publicState;
	}

	/**
	 * 公開設定 を取得します.
	 * 
	 * @return 公開設定
	 */
	public Integer getPublicState() {
		return this.publicState;
	}

	/**
	 * 公開開始日時 を設定します.
	 * 
	 * @param publicStartDate
	 *            公開開始日時
	 */
	public void setPublicStartDate(Date publicStartDate) {
		this.publicStartDate = publicStartDate;
	}

	/**
	 * 公開開始日時 を取得します.
	 * 
	 * @return 公開開始日時
	 */
	public Date getPublicStartDate() {
		return this.publicStartDate;
	}

	/**
	 * 公開終了日時 を設定します.
	 * 
	 * @param publicEndDate
	 *            公開終了日時
	 */
	public void setPublicEndDate(Date publicEndDate) {
		this.publicEndDate = publicEndDate;
	}

	/**
	 * 公開終了日時 を取得します.
	 * 
	 * @return 公開終了日時
	 */
	public Date getPublicEndDate() {
		return this.publicEndDate;
	}


}
