package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 問題イイネテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class QuestionGoodTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 問題テーブル. */
	private QuestionTblEntity questionTbl;

	/** ユーザー. */
	private UserTblEntity userTbl;

	/** イイネをした日時. */
	private Date goodDate;

	/**
	 * コンストラクタ.
	 */
	public QuestionGoodTblEntity() {
	}

	/**
	 * 問題テーブル を設定します.
	 * 
	 * @param questionTbl
	 *            問題テーブル
	 */
	public void setQuestionTbl(QuestionTblEntity questionTbl) {
		this.questionTbl = questionTbl;
	}

	/**
	 * 問題テーブル を取得します.
	 * 
	 * @return 問題テーブル
	 */
	public QuestionTblEntity getQuestionTbl() {
		return this.questionTbl;
	}

	/**
	 * ユーザー を設定します.
	 * 
	 * @param userTbl
	 *            ユーザー
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザー を取得します.
	 * 
	 * @return ユーザー
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * イイネをした日時 を設定します.
	 * 
	 * @param goodDate
	 *            イイネをした日時
	 */
	public void setGoodDate(Date goodDate) {
		this.goodDate = goodDate;
	}

	/**
	 * イイネをした日時 を取得します.
	 * 
	 * @return イイネをした日時
	 */
	public Date getGoodDate() {
		return this.goodDate;
	}


}
