package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;

/**
 * スキルと課題のテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SkillAssTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** skill_ass_id. */
	private Integer skillAssId;

	/** 問題テーブル. */
	private AssignmentTblEntity assignmentTbl;

	/** スキルテーブル. */
	private SkillTblEntity skillTbl;

	/**
	 * コンストラクタ.
	 */
	public SkillAssTblEntity() {
	}

	/**
	 * skill_ass_id を設定します.
	 * 
	 * @param skillAssId
	 *            skill_ass_id
	 */
	public void setSkillAssId(Integer skillAssId) {
		this.skillAssId = skillAssId;
	}

	/**
	 * skill_ass_id を取得します.
	 * 
	 * @return skill_ass_id
	 */
	public Integer getSkillAssId() {
		return this.skillAssId;
	}

	/**
	 * 問題テーブル を設定します.
	 * 
	 * @param assignmentTbl
	 *            問題テーブル
	 */
	public void setAssignmentTbl(AssignmentTblEntity assignmentTbl) {
		this.assignmentTbl = assignmentTbl;
	}

	/**
	 * 問題テーブル を取得します.
	 * 
	 * @return 問題テーブル
	 */
	public AssignmentTblEntity getAssignmentTbl() {
		return this.assignmentTbl;
	}

	/**
	 * スキルテーブル を設定します.
	 * 
	 * @param skillTbl
	 *            スキルテーブル
	 */
	public void setSkillTbl(SkillTblEntity skillTbl) {
		this.skillTbl = skillTbl;
	}

	/**
	 * スキルテーブル を取得します.
	 * 
	 * @return スキルテーブル
	 */
	public SkillTblEntity getSkillTbl() {
		return this.skillTbl;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((skillAssId == null) ? 0 : skillAssId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SkillAssTblEntity other = (SkillAssTblEntity) obj;
		if (skillAssId == null) {
			if (other.skillAssId != null) {
				return false;
			}
		} else if (!skillAssId.equals(other.skillAssId)) {
			return false;
		}
		return true;
	}

}
