package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * スキルテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SkillTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** スキルID. */
	private Integer skillId;

	/** スキル名. */
	private String name;

	/** update_date. */
	private Date updateDate;

	/** スキルと課題のテーブル 一覧. */
	private Set<SkillAssTblEntity> skillAssTblSet;

	/** スキルマップ 一覧. */
	private Set<SkillMapTblEntity> skillMapTblSet;

	/**
	 * コンストラクタ.
	 */
	public SkillTblEntity() {
		this.skillAssTblSet = new HashSet<SkillAssTblEntity>();
		this.skillMapTblSet = new HashSet<SkillMapTblEntity>();
	}

	/**
	 * スキルID を設定します.
	 * 
	 * @param skillId
	 *            スキルID
	 */
	public void setSkillId(Integer skillId) {
		this.skillId = skillId;
	}

	/**
	 * スキルID を取得します.
	 * 
	 * @return スキルID
	 */
	public Integer getSkillId() {
		return this.skillId;
	}

	/**
	 * スキル名 を設定します.
	 * 
	 * @param name
	 *            スキル名
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * スキル名 を取得します.
	 * 
	 * @return スキル名
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * update_date を設定します.
	 * 
	 * @param updateDate
	 *            update_date
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * update_date を取得します.
	 * 
	 * @return update_date
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * スキルと課題のテーブル 一覧を設定します.
	 * 
	 * @param skillAssTblSet
	 *            スキルと課題のテーブル 一覧
	 */
	public void setSkillAssTblSet(Set<SkillAssTblEntity> skillAssTblSet) {
		this.skillAssTblSet = skillAssTblSet;
	}

	/**
	 * スキルと課題のテーブル を追加します.
	 * 
	 * @param skillAssTbl
	 *            スキルと課題のテーブル
	 */
	public void addSkillAssTbl(SkillAssTblEntity skillAssTbl) {
		this.skillAssTblSet.add(skillAssTbl);
	}

	/**
	 * スキルと課題のテーブル 一覧を取得します.
	 * 
	 * @return スキルと課題のテーブル 一覧
	 */
	public Set<SkillAssTblEntity> getSkillAssTblSet() {
		return this.skillAssTblSet;
	}

	/**
	 * スキルマップ 一覧を設定します.
	 * 
	 * @param skillMapTblSet
	 *            スキルマップ 一覧
	 */
	public void setSkillMapTblSet(Set<SkillMapTblEntity> skillMapTblSet) {
		this.skillMapTblSet = skillMapTblSet;
	}

	/**
	 * スキルマップ を追加します.
	 * 
	 * @param skillMapTbl
	 *            スキルマップ
	 */
	public void addSkillMapTbl(SkillMapTblEntity skillMapTbl) {
		this.skillMapTblSet.add(skillMapTbl);
	}

	/**
	 * スキルマップ 一覧を取得します.
	 * 
	 * @return スキルマップ 一覧
	 */
	public Set<SkillMapTblEntity> getSkillMapTblSet() {
		return this.skillMapTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((skillId == null) ? 0 : skillId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SkillTblEntity other = (SkillTblEntity) obj;
		if (skillId == null) {
			if (other.skillId != null) {
				return false;
			}
		} else if (!skillId.equals(other.skillId)) {
			return false;
		}
		return true;
	}

}
