package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;

/**
 * スキルマップ モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SkillMapTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** skillmap_id. */
	private Integer skillmapId;

	/** ユーザー. */
	private UserTblEntity userTbl;

	/** スキルテーブル. */
	private SkillTblEntity skillTbl;

	/** point. */
	private Integer point;

	/**
	 * コンストラクタ.
	 */
	public SkillMapTblEntity() {
	}

	/**
	 * skillmap_id を設定します.
	 * 
	 * @param skillmapId
	 *            skillmap_id
	 */
	public void setSkillmapId(Integer skillmapId) {
		this.skillmapId = skillmapId;
	}

	/**
	 * skillmap_id を取得します.
	 * 
	 * @return skillmap_id
	 */
	public Integer getSkillmapId() {
		return this.skillmapId;
	}

	/**
	 * ユーザー を設定します.
	 * 
	 * @param userTbl
	 *            ユーザー
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザー を取得します.
	 * 
	 * @return ユーザー
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * スキルテーブル を設定します.
	 * 
	 * @param skillTbl
	 *            スキルテーブル
	 */
	public void setSkillTbl(SkillTblEntity skillTbl) {
		this.skillTbl = skillTbl;
	}

	/**
	 * スキルテーブル を取得します.
	 * 
	 * @return スキルテーブル
	 */
	public SkillTblEntity getSkillTbl() {
		return this.skillTbl;
	}

	/**
	 * point を設定します.
	 * 
	 * @param point
	 *            point
	 */
	public void setPoint(Integer point) {
		this.point = point;
	}

	/**
	 * point を取得します.
	 * 
	 * @return point
	 */
	public Integer getPoint() {
		return this.point;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((skillmapId == null) ? 0 : skillmapId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SkillMapTblEntity other = (SkillMapTblEntity) obj;
		if (skillmapId == null) {
			if (other.skillmapId != null) {
				return false;
			}
		} else if (!skillmapId.equals(other.skillmapId)) {
			return false;
		}
		return true;
	}

}
