package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;

/**
 * テストケースごとの答えテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TestCaseAnswerTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** testcase_answer_id. */
	private Integer testcaseAnswerId;

	/** テストケース. */
	private TestCaseTblEntity testCaseTbl;

	/** 解答テーブル. */
	private AnswerTblEntity answerTbl;

	/** 正解かどうか. */
	private Integer correctly;

	/** 解答者の出力結果. */
	private String userOutput;

	/**
	 * コンストラクタ.
	 */
	public TestCaseAnswerTblEntity() {
	}

	/**
	 * testcase_answer_id を設定します.
	 * 
	 * @param testcaseAnswerId
	 *            testcase_answer_id
	 */
	public void setTestcaseAnswerId(Integer testcaseAnswerId) {
		this.testcaseAnswerId = testcaseAnswerId;
	}

	/**
	 * testcase_answer_id を取得します.
	 * 
	 * @return testcase_answer_id
	 */
	public Integer getTestcaseAnswerId() {
		return this.testcaseAnswerId;
	}

	/**
	 * テストケース を設定します.
	 * 
	 * @param testCaseTbl
	 *            テストケース
	 */
	public void setTestCaseTbl(TestCaseTblEntity testCaseTbl) {
		this.testCaseTbl = testCaseTbl;
	}

	/**
	 * テストケース を取得します.
	 * 
	 * @return テストケース
	 */
	public TestCaseTblEntity getTestCaseTbl() {
		return this.testCaseTbl;
	}

	/**
	 * 解答テーブル を設定します.
	 * 
	 * @param answerTbl
	 *            解答テーブル
	 */
	public void setAnswerTbl(AnswerTblEntity answerTbl) {
		this.answerTbl = answerTbl;
	}

	/**
	 * 解答テーブル を取得します.
	 * 
	 * @return 解答テーブル
	 */
	public AnswerTblEntity getAnswerTbl() {
		return this.answerTbl;
	}

	/**
	 * 正解かどうか を設定します.
	 * 
	 * @param correctly
	 *            正解かどうか
	 */
	public void setCorrectly(Integer correctly) {
		this.correctly = correctly;
	}

	/**
	 * 正解かどうか を取得します.
	 * 
	 * @return 正解かどうか
	 */
	public Integer getCorrectly() {
		return this.correctly;
	}

	/**
	 * 解答者の出力結果 を設定します.
	 * 
	 * @param userOutput
	 *            解答者の出力結果
	 */
	public void setUserOutput(String userOutput) {
		this.userOutput = userOutput;
	}

	/**
	 * 解答者の出力結果 を取得します.
	 * 
	 * @return 解答者の出力結果
	 */
	public String getUserOutput() {
		return this.userOutput;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((testcaseAnswerId == null) ? 0 : testcaseAnswerId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TestCaseAnswerTblEntity other = (TestCaseAnswerTblEntity) obj;
		if (testcaseAnswerId == null) {
			if (other.testcaseAnswerId != null) {
				return false;
			}
		} else if (!testcaseAnswerId.equals(other.testcaseAnswerId)) {
			return false;
		}
		return true;
	}

}
