package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;

/**
 * ユーザー称号テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserLevelTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** user_level_id. */
	private Integer userLevelId;

	/** 称号マスターテーブル. */
	private LevelTblEntity levelTbl;

	/** ユーザー. */
	private UserTblEntity userTbl;

	/**
	 * コンストラクタ.
	 */
	public UserLevelTblEntity() {
	}

	/**
	 * user_level_id を設定します.
	 * 
	 * @param userLevelId
	 *            user_level_id
	 */
	public void setUserLevelId(Integer userLevelId) {
		this.userLevelId = userLevelId;
	}

	/**
	 * user_level_id を取得します.
	 * 
	 * @return user_level_id
	 */
	public Integer getUserLevelId() {
		return this.userLevelId;
	}

	/**
	 * 称号マスターテーブル を設定します.
	 * 
	 * @param levelTbl
	 *            称号マスターテーブル
	 */
	public void setLevelTbl(LevelTblEntity levelTbl) {
		this.levelTbl = levelTbl;
	}

	/**
	 * 称号マスターテーブル を取得します.
	 * 
	 * @return 称号マスターテーブル
	 */
	public LevelTblEntity getLevelTbl() {
		return this.levelTbl;
	}

	/**
	 * ユーザー を設定します.
	 * 
	 * @param userTbl
	 *            ユーザー
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザー を取得します.
	 * 
	 * @return ユーザー
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userLevelId == null) ? 0 : userLevelId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		UserLevelTblEntity other = (UserLevelTblEntity) obj;
		if (userLevelId == null) {
			if (other.userLevelId != null) {
				return false;
			}
		} else if (!userLevelId.equals(other.userLevelId)) {
			return false;
		}
		return true;
	}

}
