package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;


import lombok.Data;

/**
 * 問題イイネテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="ASSIGNMENT_GOOD_TBL")
public class AssignmentGoodTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer assignmentGoodId;
	
	private Integer assignmentId;	//挿入・更新用
	private Integer userId;	//挿入・更新用
	
	/** 問題テーブル. */
	@OneToOne
    @JoinColumn(name="assignmentId",insertable=false ,updatable=false)
	private AssignmentTblEntity assignmentTbl;

	/** ユーザー. */
	@OneToOne
    @JoinColumn(name="userId",insertable=false ,updatable=false)
	private UserTblEntity userTbl;

	/** イイネをした日時. */
	private Date goodDate;

	/**
	 * コンストラクタ.
	 */
	public AssignmentGoodTblEntity() {
	}

	/**
	 * 問題テーブル を設定します.
	 * 
	 * @param assignmentTbl
	 *            問題テーブル
	 */
	public void setAssignmentTbl(AssignmentTblEntity assignmentTbl) {
		this.assignmentTbl = assignmentTbl;
	}

	/**
	 * 問題テーブル を取得します.
	 * 
	 * @return 問題テーブル
	 */
	public AssignmentTblEntity getAssignmentTbl() {
		return this.assignmentTbl;
	}

	/**
	 * ユーザー を設定します.
	 * 
	 * @param userTbl
	 *            ユーザー
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザー を取得します.
	 * 
	 * @return ユーザー
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * イイネをした日時 を設定します.
	 * 
	 * @param goodDate
	 *            イイネをした日時
	 */
	public void setGoodDate(Date goodDate) {
		this.goodDate = goodDate;
	}

	/**
	 * イイネをした日時 を取得します.
	 * 
	 * @return イイネをした日時
	 */
	public Date getGoodDate() {
		return this.goodDate;
	}


}
