package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;


import lombok.Data;

/**
 * 問題イイネテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="ASSIGNMENT_GOOD_TBL")
public class AssignmentGoodTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer assignmentGoodId;
	
	private Integer assignmentId;	//挿入・更新用
	private Integer userId;	//挿入・更新用
	
	/** ユーザー. */
	@OneToOne
    @JoinColumn(name="userId",insertable=false ,updatable=false)
	private UserTblEntity userTbl;

	/** イイネをした日時. */
	private Date goodDate;

	/**
	 * コンストラクタ.
	 */
	public AssignmentGoodTblEntity() {
	}


}
