package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;


import lombok.Data;

/**
 * コメント モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="COMMENT_TBL")
public class CommentTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer comment_id;

	private Integer answerId;	//挿入・更新用
	/** 解答テーブル. */
	@OneToOne
    @JoinColumn(name="answerId",insertable=false ,updatable=false)
	private AnswerTblEntity answerTbl;

	/** ユーザー. */
	private Integer userId;	//挿入・更新用
	@OneToOne
    @JoinColumn(name="userId",insertable=false ,updatable=false)
	private UserTblEntity userTbl;

	/** comment. */
	private String comment;

	/** entry_date. */
	private Date entryDate;

	@PrePersist
    public void onPrePersist() {
		setEntryDate(new Date());
    }

    @PreUpdate
    public void onPreUpdate() {
    	setEntryDate(new Date());
    }
}
