package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * 新規テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="COURSE_TBL")
public class CourseTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** course_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer courseId;

	/** 学科名. */
	private String name;

	/** 年数. */
	private Integer year;

	/** 新規テーブル 一覧. */
	//private Set<HomeroomTblEntity> homeroomTblSet;

	/** 公開設定 一覧. */
	//private Set<PublicQuestionTblEntity> publicQuestionTblSet;

	/**
	 * コンストラクタ.
	 */
	public CourseTblEntity() {
		//this.homeroomTblSet = new HashSet<HomeroomTblEntity>();
		//this.publicQuestionTblSet = new HashSet<PublicQuestionTblEntity>();
	}

}
