package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * フォロー モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class FollowTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ユーザー. */
	private UserTblEntity userTbl;

	/** ユーザー. */
	private UserTblEntity follewUserTbl;

	/** フォローした日. */
	private Date followDate;

	/**
	 * コンストラクタ.
	 */
	public FollowTblEntity() {
	}

	/**
	 * ユーザー を設定します.
	 * 
	 * @param userTbl
	 *            ユーザー
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザー を取得します.
	 * 
	 * @return ユーザー
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * ユーザー を設定します.
	 * 
	 * @param follewUserTbl
	 *            ユーザー
	 */
	public void setFollewUserTbl(UserTblEntity follewUserTbl) {
		this.follewUserTbl = follewUserTbl;
	}

	/**
	 * ユーザー を取得します.
	 * 
	 * @return ユーザー
	 */
	public UserTblEntity getFollewUserTbl() {
		return this.follewUserTbl;
	}

	/**
	 * フォローした日 を設定します.
	 * 
	 * @param followDate
	 *            フォローした日
	 */
	public void setFollowDate(Date followDate) {
		this.followDate = followDate;
	}

	/**
	 * フォローした日 を取得します.
	 * 
	 * @return フォローした日
	 */
	public Date getFollowDate() {
		return this.followDate;
	}


}
