package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;


import lombok.Data;

/**
 * フォロー モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="FOLLOW_TBL")
@IdClass(FollowTblId.class)
public class FollowTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	@Id
	private Integer userId;	//挿入・更新用
	@Id
	private Integer follewUserId;	//挿入・更新用
	
	/** ユーザー. */
	@OneToOne
    @JoinColumn(name="userId",insertable=false ,updatable=false)
	private UserTblEntity userTbl;

	/** ユーザー. */
	@OneToOne
    @JoinColumn(name="follewUserId",insertable=false ,updatable=false)
	private UserTblEntity follewUserTbl;

	/** フォローした日. */
	private Date followDate;

	@PrePersist
    public void onPrePersist() {
		setFollowDate(new Date());
    }

    @PreUpdate
    public void onPreUpdate() {
    	setFollowDate(new Date());
    }
}
