package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;


import lombok.Data;

/**
 * フォロー モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="FOLLOW_TBL")
public class FollowTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	@Id
	private Integer userId;	//挿入・更新用
	@Id
	private Integer follewUserId;	//挿入・更新用
	
	/** ユーザー. */
	@OneToOne
    @JoinColumn(name="userId",insertable=false ,updatable=false)
	private UserTblEntity userTbl;

	/** ユーザー. */
	@OneToOne
    @JoinColumn(name="follewUserId",insertable=false ,updatable=false)
	private UserTblEntity follewUserTbl;

	/** フォローした日. */
	private Date followDate;

	/**
	 * コンストラクタ.
	 */
	public FollowTblEntity() {
	}

	/**
	 * ユーザー を設定します.
	 * 
	 * @param userTbl
	 *            ユーザー
	 */
	public void setUserTbl(UserTblEntity userTbl) {
		this.userTbl = userTbl;
	}

	/**
	 * ユーザー を取得します.
	 * 
	 * @return ユーザー
	 */
	public UserTblEntity getUserTbl() {
		return this.userTbl;
	}

	/**
	 * ユーザー を設定します.
	 * 
	 * @param follewUserTbl
	 *            ユーザー
	 */
	public void setFollewUserTbl(UserTblEntity follewUserTbl) {
		this.follewUserTbl = follewUserTbl;
	}

	/**
	 * ユーザー を取得します.
	 * 
	 * @return ユーザー
	 */
	public UserTblEntity getFollewUserTbl() {
		return this.follewUserTbl;
	}

	/**
	 * フォローした日 を設定します.
	 * 
	 * @param followDate
	 *            フォローした日
	 */
	public void setFollowDate(Date followDate) {
		this.followDate = followDate;
	}

	/**
	 * フォローした日 を取得します.
	 * 
	 * @return フォローした日
	 */
	public Date getFollowDate() {
		return this.followDate;
	}


}
