package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 問題グループ モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GroupTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** qgroup_id. */
	private Integer qgroupId;

	/** グループ名. */
	private String name;

	/** 登録日時. */
	private Date entryDate;

	/** 更新日時. */
	private Date updateDate;

	/** 問題テーブル 一覧. */
	private Set<AssignmentTblEntity> questionTblSet;

	/**
	 * コンストラクタ.
	 */
	public GroupTblEntity() {
		this.questionTblSet = new HashSet<AssignmentTblEntity>();
	}

	/**
	 * qgroup_id を設定します.
	 * 
	 * @param qgroupId
	 *            qgroup_id
	 */
	public void setQgroupId(Integer qgroupId) {
		this.qgroupId = qgroupId;
	}

	/**
	 * qgroup_id を取得します.
	 * 
	 * @return qgroup_id
	 */
	public Integer getQgroupId() {
		return this.qgroupId;
	}

	/**
	 * グループ名 を設定します.
	 * 
	 * @param name
	 *            グループ名
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * グループ名 を取得します.
	 * 
	 * @return グループ名
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 登録日時 を設定します.
	 * 
	 * @param entryDate
	 *            登録日時
	 */
	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	/**
	 * 登録日時 を取得します.
	 * 
	 * @return 登録日時
	 */
	public Date getEntryDate() {
		return this.entryDate;
	}

	/**
	 * 更新日時 を設定します.
	 * 
	 * @param updateDate
	 *            更新日時
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * 更新日時 を取得します.
	 * 
	 * @return 更新日時
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * 問題テーブル 一覧を設定します.
	 * 
	 * @param questionTblSet
	 *            問題テーブル 一覧
	 */
	public void setQuestionTblSet(Set<AssignmentTblEntity> questionTblSet) {
		this.questionTblSet = questionTblSet;
	}

	/**
	 * 問題テーブル を追加します.
	 * 
	 * @param questionTbl
	 *            問題テーブル
	 */
	public void addQuestionTbl(AssignmentTblEntity questionTbl) {
		this.questionTblSet.add(questionTbl);
	}

	/**
	 * 問題テーブル 一覧を取得します.
	 * 
	 * @return 問題テーブル 一覧
	 */
	public Set<AssignmentTblEntity> getQuestionTblSet() {
		return this.questionTblSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((qgroupId == null) ? 0 : qgroupId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		GroupTblEntity other = (GroupTblEntity) obj;
		if (qgroupId == null) {
			if (other.qgroupId != null) {
				return false;
			}
		} else if (!qgroupId.equals(other.qgroupId)) {
			return false;
		}
		return true;
	}

}
