package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;

import lombok.Data;

/**
 * 問題グループ モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="GROUP_TBL")
public class GroupTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** group_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer groupId;

	/** グループ名. */
	private String name;

	/** 登録日時. */
	private Date entryDate;

	/** 更新日時. */
	private Date updateDate;

	/** 問題テーブル 一覧. */
	//private Set<AssignmentTblEntity> questionTblSet;

	@PrePersist
    public void onPrePersist() {
		setEntryDate(new Date());
		setUpdateDate(new Date());
    }

    @PreUpdate
    public void onPreUpdate() {
    	setUpdateDate(new Date());
    }
}
