package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * 新規テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="HOMEROOM_TBL")
public class HomeroomTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** homeroom_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer homeroomId;

	/** 新規テーブル. */
    @OneToOne
    @JoinColumn(name="courseId")
	private CourseTblEntity courseTbl;

	/** クラス名. */
	private String name;



}
