package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * 称号マスターテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="LEVEL_TBL")
public class LevelTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** level_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer levelId;

	/** 称号名. */
	private String name;

	/** 説明. */
	private String description;


}
