package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 公開設定 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PublicQuestionTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 問題テーブル. */
	private QuestionTblEntity questionTbl;

	/** 新規テーブル. */
	private CourseTblEntity courseTbl;

	/** 新規テーブル. */
	private HomeroomTblEntity homeroomTbl;

	/** 公開開始日時. */
	private Date publicStartDate;

	/** 公開終了日時. */
	private Date publicEndDate;

	/**
	 * コンストラクタ.
	 */
	public PublicQuestionTblEntity() {
	}

	/**
	 * 問題テーブル を設定します.
	 * 
	 * @param questionTbl
	 *            問題テーブル
	 */
	public void setQuestionTbl(QuestionTblEntity questionTbl) {
		this.questionTbl = questionTbl;
	}

	/**
	 * 問題テーブル を取得します.
	 * 
	 * @return 問題テーブル
	 */
	public QuestionTblEntity getQuestionTbl() {
		return this.questionTbl;
	}

	/**
	 * 新規テーブル を設定します.
	 * 
	 * @param courseTbl
	 *            新規テーブル
	 */
	public void setCourseTbl(CourseTblEntity courseTbl) {
		this.courseTbl = courseTbl;
	}

	/**
	 * 新規テーブル を取得します.
	 * 
	 * @return 新規テーブル
	 */
	public CourseTblEntity getCourseTbl() {
		return this.courseTbl;
	}

	/**
	 * 新規テーブル を設定します.
	 * 
	 * @param homeroomTbl
	 *            新規テーブル
	 */
	public void setHomeroomTbl(HomeroomTblEntity homeroomTbl) {
		this.homeroomTbl = homeroomTbl;
	}

	/**
	 * 新規テーブル を取得します.
	 * 
	 * @return 新規テーブル
	 */
	public HomeroomTblEntity getHomeroomTbl() {
		return this.homeroomTbl;
	}

	/**
	 * 公開開始日時 を設定します.
	 * 
	 * @param publicStartDate
	 *            公開開始日時
	 */
	public void setPublicStartDate(Date publicStartDate) {
		this.publicStartDate = publicStartDate;
	}

	/**
	 * 公開開始日時 を取得します.
	 * 
	 * @return 公開開始日時
	 */
	public Date getPublicStartDate() {
		return this.publicStartDate;
	}

	/**
	 * 公開終了日時 を設定します.
	 * 
	 * @param publicEndDate
	 *            公開終了日時
	 */
	public void setPublicEndDate(Date publicEndDate) {
		this.publicEndDate = publicEndDate;
	}

	/**
	 * 公開終了日時 を取得します.
	 * 
	 * @return 公開終了日時
	 */
	public Date getPublicEndDate() {
		return this.publicEndDate;
	}


}
