package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;


import lombok.Data;

/**
 * 公開設定 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="PUBLIC_ASSIGNMENT_TBL")
public class PublicAssignmentTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer publicAssignmentId;
	
	private Integer assignmentId;	//挿入・更新用
	private Integer homeroomId;	//挿入・更新用
	
	/** 問題テーブル. */
	@OneToOne
    @JoinColumn(name="assignmentId",insertable=false ,updatable=false)
	private AssignmentTblEntity assignmentTbl;

	/** 新規テーブル. */
	@OneToOne
    @JoinColumn(name="homeroomId",insertable=false ,updatable=false)
	private HomeroomTblEntity homeroomTbl;

	/** 公開設定. */
	private Integer publicState;

	/** 公開開始日時. */
	private Date publicStartDate;

	/** 公開終了日時. */
	private Date publicEndDate;

	/**
	 * コンストラクタ.
	 */
	public PublicAssignmentTblEntity() {
	}


}
