package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * スキルマップ モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
 @Entity 
 @Table(name="SKILL_MAP_TBL")
public class SkillMapTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** skillmap_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer skillmapId;

	/** ユーザー. */
	private Integer userId;

	/** スキルテーブル. */
	private Integer skillId;
	@OneToOne
    @JoinColumn(name="skillId",insertable=false ,updatable=false)
	private SkillTblEntity skillTbl;

	/** point. */
	private Integer point;

}
