package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * テストケース モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="TEST_CASE_TBL")
public class TestCaseTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer testcaseId;

	/** 問題テーブル. */
	private Integer assignmentId;

	/** テスト番号. */
	private Integer no;

	/** テストの入力値. */
	private String inputText;

	/** 出力値. */
	private String outputTxt;


}
