package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * テストケースごとの答えテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="TEST_CASE_ANSWER_TBL")
public class TestCaseAnswerTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** testcase_answer_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer testcaseAnswerId;

	/** テストケース. */
	private Integer testcaseId;	//更新用
	@OneToOne
    @JoinColumn(name="testcaseId",insertable=false ,updatable=false)
	private TestCaseTblEntity testCaseTbl;

	/** 解答テーブル. */
	private Integer answerId;	//更新用

	/** 正解かどうか. */
	private Integer correctly;

	/** 解答者の出力結果. */
	private String userOutput;

}
