package jp.ac.asojuku.azcafe.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * ユーザー称号テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="USER_LEVEL_TBL")
public class UserLevelTblEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** user_level_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer userLevelId;

	/** 称号マスターテーブル. */
	private Integer levelId;	//更新用
    @OneToOne
    @JoinColumn(name="levelId" ,insertable=false ,updatable=false)
	private LevelTblEntity levelTbl;

	/** ユーザー. */
	private Integer userId;

}
