spring:
  servlet:
    multipart:
      max-file-size: 3MB
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/azcafe?serverTimezone=JST
    username: root
    password: Abcc123.#
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: nishino.aso@gmail.com
    password: jizlzeuhkrorsarh
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    
azcafe:
  salt: 5fr2FjxT
  avaterbasedir: /var/azcafe/img
  tokenlimit: 1
  passwordpolicy: 
  csvoutputdir: /var/azcafe/output
  csvoutputencode: Shift_JIS
  csvuploaddir: /var/azcafe/upload
  batchdir: /var/azcafe/batch
  batchfileext: bat 
  codedir: /var/azcafe/code
  srcPrefix: src_
  gradingjavac: comple_java.sh
  gradingjava: exec_java.sh
  checkstyle: checkstyle_java.sh
  gradingjavascript: exec_javascript.sh
  skillmaplimit: 100
  studentdenied: ^/user/reset/password$,^/homeroom/update,^/assignment/(edit|create|confirm|insert),^/manage/.*,^user/csvinput
  nologindisplay: /,/login,/auth,/logout,/css/.+,/img/.+,/getImage/.+,/favicon.ico,/error/.*,/js/.+,/dist/.+,/plugins/.+,/summernote/.+
  handminus: 0
  difficulty:
    veasy: 0
    easy: 2
    normal: 5
    diff: 7
    vdiff: 10